global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "superset"
    static_configs:
      - targets: ["superset:8088"]

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "cube"
    metrics_path: "/metrics" # Verify if Cube exposes metrics at root or /metrics
    static_configs:
      - targets: ["cube:4000"]

  - job_name: "prefect"
    static_configs:
      - targets: ["prefect:4200"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
