global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "superset"
    static_configs:
      - targets: ["statsd-exporter:9102"]

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "cube"
    static_configs:
      - targets: ["statsd-exporter:9102"] # Cube metrics can also flow through statsd

  - job_name: "prefect"
    metrics_path: /metrics
    static_configs:
      - targets: ["prefect:4200"]

  - job_name: "cadvisor"
    metrics_path: /cadvisor/metrics
    static_configs:
      - targets: ["cadvisor:8080"]
